// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGrpfJWJdYy4Z34zRFhaBDASIqc4Nn4w',
    appId: '1:535627715101:web:b11b8f1d41439e816aecf4',
    messagingSenderId: '535627715101',
    projectId: 'pomodoro-b88d5',
    authDomain: 'pomodoro-b88d5.firebaseapp.com',
    storageBucket: 'pomodoro-b88d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFmoG5eb4L_DznC6iwuFIzvxkdHG4LRc',
    appId: '1:535627715101:android:813a13d2bf5f65a06aecf4',
    messagingSenderId: '535627715101',
    projectId: 'pomodoro-b88d5',
    storageBucket: 'pomodoro-b88d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbwOgCbrOfg9GA3-Itw4iHIKfGApqSSvA',
    appId: '1:535627715101:ios:c7e1ddb3e542dca96aecf4',
    messagingSenderId: '535627715101',
    projectId: 'pomodoro-b88d5',
    storageBucket: 'pomodoro-b88d5.appspot.com',
    androidClientId: '535627715101-k39q7q3m4ttn09po45nefpaptdg56dkj.apps.googleusercontent.com',
    iosClientId: '535627715101-00u8k2b73p5fknenafgg2uvhnuo8ak78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbwOgCbrOfg9GA3-Itw4iHIKfGApqSSvA',
    appId: '1:535627715101:ios:c7e1ddb3e542dca96aecf4',
    messagingSenderId: '535627715101',
    projectId: 'pomodoro-b88d5',
    storageBucket: 'pomodoro-b88d5.appspot.com',
    androidClientId: '535627715101-k39q7q3m4ttn09po45nefpaptdg56dkj.apps.googleusercontent.com',
    iosClientId: '535627715101-00u8k2b73p5fknenafgg2uvhnuo8ak78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRGrpfJWJdYy4Z34zRFhaBDASIqc4Nn4w',
    appId: '1:535627715101:web:9c1995d57bed59786aecf4',
    messagingSenderId: '535627715101',
    projectId: 'pomodoro-b88d5',
    authDomain: 'pomodoro-b88d5.firebaseapp.com',
    storageBucket: 'pomodoro-b88d5.appspot.com',
  );
}
